### ISSUE TITLE
Utilisation dans Jeedom

### ISSUE THREAD

**Issue by dsigmoun** [LeClubber/iDiamant2Mqtt#4]
Bonjour,

J'essaie d'intégrer Idiamant2MQTT.
J'ai vérifié toutes mes infos et tout est OK de ce côté

Cependant, dans les logs, j'ai ces informations.

```
2024-09-14T16:32:06.556918357Z Traceback (most recent call last):
2024-09-14T16:32:06.556971716Z   File "/usr/src/idiamant/server.py", line 10, in 
2024-09-14T16:32:06.557054549Z     iDiamant.initDiscovery()
2024-09-14T16:32:06.557091216Z   File "/usr/src/idiamant/idiamant.py", line 25, in initDiscovery
2024-09-14T16:32:06.557282862Z     homes = jsonStatus['body']['homes']
2024-09-14T16:32:06.557361853Z             ~~~~~~~~~~^^^^^^^^
2024-09-14T16:32:06.557395657Z KeyError: 'body'
```

Avez-vous une idée de l'origine du problème ?

Bien cordialement,
Frédéric

**Comment by dsigmoun** [comment]
bon, j'ai regénéré les token, cela semble fonctionner maintenant.
